---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: tool-pv
      namespace: tool
      labels:
        app: tool-pv
    spec:
      capacity:
        storage: 100Gi
      accessModes:
        - ReadWriteMany
      nfs:
        server: x.x.x.x
        path: /data05/nfs
      persistentVolumeReclaimPolicy: Retain

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: tool-pvc
      namespace: tool
      labels:
        app: tool-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
 
  - apiVersion: "apps/v1beta1"
    kind: "Deployment"
    metadata:
      name: "tool-upload"
      namespace: "tool"
      labels:
        name: "tool-upload"
    spec:
      replicas: 1
      template:
        metadata:
          name: "tool-upload"
          labels:
            name: "tool-upload"
        spec:
          volumes:
            - name: upload
              persistentVolumeClaim:
                claimName: tool-pvc
          containers:
            - name: "tool-upload"
              image: "tool-upload:v0.1"
              ports:
                - containerPort: 5000
              volumeMounts:
                - name: upload
                  mountPath: /usr/src/app/uploads
                  subPath: tool_uploads
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "tool-upload"
      namespace: "tool"
    spec:
      type: "NodePort"
      selector:
        name: "tool-upload"
      ports:
        -
          name: "http"
          port: 5000
          protocol: "TCP"
